### ISSUE TITLE
Allow addition of extensions

### ISSUE THREAD

**Issue by Elizafox** [Elizafox/PyIRC#1]
Extensions cannot be added without deleting all existing ones at runtime. This is an impediment to dynamically loading extensions later. Should probably be done similar to deletion.

**Comment by awilfox** [comment]
What should happen if an addition is already added?  Should it behave as [require does, in other languages](http://ruby-doc.org/core-2.1.1/Kernel.html#method-i-require) (i.e. do nothing)?  Should it reload the extension?  Should it raise (possibly ImportError: Cannot load an extension twice)?  Warn but not raise?  Some other behaviour I haven't said?

Personally, I feel reloading extensions should be a little more explicit than "call add again".  Warning (or doing nothing) is probably the least surprising.

**Comment by Elizafox** [comment]
Python lets you import things multiple times and it doesn't care, but second imports do nothing. Probably best to follow that behaviour.

**Comment by Elizafox** [comment]
The new event system lets you do this as of 5e77a34291 rendering this obsolete.
